"""Generate a tikzpicture of GMLVQ as Siamese network."""
import datetime
import os

from mako.template import Template

with open("../templates/siamese-net.template") as f:
    content = f.read()
    template = Template(text=content)

out = template.render(
    header=f"Generated by ninaa on {datetime.datetime.now().ctime()}.",
    png=True,
    input_color="black",
    input_scale=1.0,
    text_width=50,
    input_1=r"\verb!Inputs!",
    input_2=r"\verb!Prototypes!",
    shared_block=r"$\mathbf{\Omega}$",
    fc=False,
    dissimilarity=r"\verb!Distance Layer!",
    loss="GLVQ Loss",
)
with open("siamese-gmlvq.tex", "w+") as f:
    f.write(out)

os.system("pdflatex -shell-escape siamese-gmlvq.tex")
